apiVersion: v1
kind: PersistentVolume
metadata:
  name: hf-data-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: "{{ .Values.engine.pv.storageCapacity }}"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: "{{ .Values.engine.pv.storageClass }}"
  hostPath:
    path: /mnt/data/hf-data
    type: DirectoryOrCreate
