apiVersion: v1
kind: Service
metadata:
  name: flex-frog-ui
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: flex-frog-ui
  ports:
    - protocol: TCP
      port: {{ .Values.ui.port }}
      targetPort: {{ .Values.ui.port }}
      nodePort: {{ .Values.ui.nodePort }}

