apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-data-pv
  namespace: {{ .Values.namespace }}
spec:
  capacity:
    storage: "{{.Values.postgres.pv.storageCapacity }}"
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: "{{ .Values.postgres.pv.storageClass }}"
  hostPath:
    path: /mnt/data/db-data
    type: DirectoryOrCreate
