apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hf-data-pvc
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.engine.pv.storageCapacity }}"
  storageClassName: "{{ .Values.engine.pv.storageClass }}"
