apiVersion: v1
kind: Service
metadata:
  name: flex-frog-db
  namespace: "{{ .Values.namespace }}"
spec:
  selector:
    app: flex-frog-db
  ports:
    - port: 5432
      targetPort: {{ .Values.postgres.port }}
      protocol: TCP
